apiVersion: apps/v1
kind: Deployment
metadata:
  name: candycrush-deployment
  labels:
    app: candycrush
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candycrush
  template:
    metadata:
      labels:
        app: candycrush
    spec:
      containers:
      - name: candycrush
        image: godwinchinedu/candycrush:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
