apiVersion: v1
kind: Service
metadata:
  name: candycrush-service
  labels:
    app: candycrush
spec:
  type: NodePort
  selector:
    app: candycrush
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30007
